// <auto-generated />
using System;
using FinalBankExampleCore.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalBankExampleCore.Migrations
{
    [DbContext(typeof(SQLDataContext))]
    partial class SQLDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalBankExampleCore.Entities.BankAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlock")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiesDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastTransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("FinalBankExampleCore.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiesDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateDate = new DateTime(2023, 1, 14, 9, 47, 27, 220, DateTimeKind.Local).AddTicks(1440),
                            FirstName = "maryam",
                            LastModifiesDate = new DateTime(2023, 1, 14, 9, 47, 27, 220, DateTimeKind.Local).AddTicks(1478),
                            LastName = "akbari",
                            Password = "mm",
                            UserName = "mm"
                        },
                        new
                        {
                            ID = 2,
                            CreateDate = new DateTime(2023, 1, 14, 9, 47, 27, 220, DateTimeKind.Local).AddTicks(1481),
                            FirstName = "zeynab",
                            LastModifiesDate = new DateTime(2023, 1, 14, 9, 47, 27, 220, DateTimeKind.Local).AddTicks(1483),
                            LastName = "shabanpour",
                            Password = "zz",
                            UserName = "zz"
                        });
                });

            modelBuilder.Entity("FinalBankExampleCore.Entities.BankAccount", b =>
                {
                    b.HasOne("FinalBankExampleCore.Entities.User", "User")
                        .WithOne("BankAccount")
                        .HasForeignKey("FinalBankExampleCore.Entities.BankAccount", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalBankExampleCore.Entities.User", b =>
                {
                    b.Navigation("BankAccount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
